# Generated by Django 5.1.2 on 2024-11-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_api', '0002_alter_document_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
